apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
       app: mysql
       tier: mysql
       project: expense
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
       app: mysql
       tier: mysql
       project: expense
    spec:
      containers:
      - name: nginx
        image: parijatha2025/mysql:1.0.0

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: expense
# spec:
#   selector:
#     app: mysql
#     tier: mysql
#     project: expense
#   ports:
#     - protocol: TCP
#       port: 3306 # service port
#       targetPort: 3306

        